In [1]:
import pandas as pd
import numpy as np

In [2]:
######### Iris Data Set ########################
iris = pd.read_csv("iris.csv")


In [3]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [4]:
ip_columns = ["Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"]
op_column  = ["Species"]


In [5]:
# Splitting data into train and test
Xtrain,Xtest,ytrain,ytest = train_test_split(iris[ip_columns],iris[op_column],test_size=0.3, random_state=0)


In [6]:
ignb = GaussianNB()
imnb = MultinomialNB()


In [12]:
# Building and predicting at the same time 

pred_gnb = ignb.fit(Xtrain,ytrain).predict(Xtest)
pred_gnb


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'setosa'], dtype='<U10')

In [13]:
pred_mnb = imnb.fit(Xtrain,ytrain).predict(Xtest)
pred_mnb


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array(['virginica', 'virginica', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'virginica', 'virginica', 'setosa', 'setosa', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'setosa', 'virginica', 'setosa', 'setosa'],
      dtype='<U10')

In [14]:
# Confusion matrix GaussianNB model
confusion_matrix(ytest,pred_gnb) # GaussianNB model


array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]], dtype=int64)

In [15]:
pd.crosstab(ytest.values.flatten(),pred_gnb) # confusion matrix using 


col_0       setosa  versicolor  virginica
row_0                                    
setosa          16           0          0
versicolor       0          18          0
virginica        0           0         11

In [16]:
np.mean(pred_gnb==ytest.values.flatten()) # 100%


1.0

In [17]:
# Confusion matrix GaussianNB model
confusion_matrix(ytest,pred_mnb) # GaussianNB model


array([[16,  0,  0],
       [ 0,  0, 18],
       [ 0,  0, 11]], dtype=int64)

In [18]:
pd.crosstab(ytest.values.flatten(),pred_mnb) # confusion matrix using 


col_0       setosa  virginica
row_0                        
setosa          16          0
versicolor       0         18
virginica        0         11

In [19]:
np.mean(pred_mnb==ytest.values.flatten()) # 60%


0.6

In [20]:
confusion_matrix(ytest,pred_mnb) # Multinomal model


array([[16,  0,  0],
       [ 0,  0, 18],
       [ 0,  0, 11]], dtype=int64)